[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "shanghai"
fs_permissions = [{ access = "read", path = "./config/" }]
gas_limit = 180000000                                      # Doubl√© pour tests fork avec chunking dynamique

# Fuzz configuration
fuzz = { runs = 1000, max_local_rejects = 10000, max_global_rejects = 10000 }
fuzz_max_local_rejects = 10000
fuzz_max_global_rejects = 10000

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true


[profile.via_ir]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
evm_version = "shanghai"

[profile.networks.mainnet]
url = "${ETH_RPC_URL}"
accounts = ["${PRIVATE_KEY}"]

[profile.networks.buildbear]
url = "https://rpc.buildbear.io/foolish-darkphoenix-2fe074ec"
accounts = ["${PRIVATE_KEY}"]
chainId = 25875

[etherscan]
mainnet = { key = "${API_KEY_ETHERSCAN}" }

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${INFURA_KEY}"
